import {
	HiArrowUpRight,
	HiOutlineLink,
	HiArrowTopRightOnSquare,
	HiEnvelope,
	HiCalendarDays,
	HiArrowRight,
	HiOutlineEye,
	HiOutlineEyeSlash,
	HiOutlineDocument,
	HiOutlineGlobeAsiaAustralia,
	HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
	PiHouseDuotone,
	PiUserCircleDuotone,
	PiGridFourDuotone,
	PiBookBookmarkDuotone,
	PiImageDuotone,
} from "react-icons/pi";

import {
	SiJavascript,
	SiNextdotjs,
	SiHtml5,
	SiReact,
	SiDocker,
	SiKubernetes,
	SiCss3,
	SiBootstrap,
	SiNodedotjs,
	SiJquery,
	SiMongodb,
	SiWechat,
	SiUnity,
	SiNginx,
	SiXiaohongshu,
	SiFigma,
	SiSupabase,
	SiFirebase,
} from "react-icons/si";

import {
	FaDiscord,
	FaGithub,
	FaYoutube,
	FaLinkedin,
	FaX,
	FaThreads,
	FaXTwitter,
	FaFacebook,
	FaPinterest,
	FaWhatsapp,
	FaReddit,
	FaTelegram,
} from "react-icons/fa6";

export const iconLibrary = {
	arrowUpRight: HiArrowUpRight,
	arrowRight: HiArrowRight,
	email: HiEnvelope,
	globe: HiOutlineGlobeAsiaAustralia,
	person: PiUserCircleDuotone,
	grid: PiGridFourDuotone,
	book: PiBookBookmarkDuotone,
	openLink: HiOutlineLink,
	calendar: HiCalendarDays,
	home: PiHouseDuotone,
	gallery: PiImageDuotone,
	discord: FaDiscord,
	eye: HiOutlineEye,
	eyeOff: HiOutlineEyeSlash,
	github: FaGithub,
	youtube: FaYoutube,
	xiaohongshu: SiXiaohongshu,
	linkedin: FaLinkedin,
	x: FaX,
	twitter: FaXTwitter,
	threads: FaThreads,
	arrowUpRightFromSquare: HiArrowTopRightOnSquare,
	document: HiOutlineDocument,
	rocket: HiOutlineRocketLaunch,
	javascript: SiJavascript,
	nextjs: SiNextdotjs,
	supabase: SiSupabase,
	figma: SiFigma,
	facebook: FaFacebook,
	pinterest: FaPinterest,
	whatsapp: FaWhatsapp,
	reddit: FaReddit,
	telegram: FaTelegram,
	html: SiHtml5,
	reactjs: SiReact,
	docker: SiDocker,
	k8s: SiKubernetes,
	css: SiCss3,
	bootstrap: SiBootstrap,
	nodejs: SiNodedotjs,
	mongodb: SiMongodb,
	wechat: SiWechat,
	unity: SiUnity,
	jquery: SiJquery,
	nginx: SiNginx,
	firebase: SiFirebase,
};
