import {
	HiArrowUpRight,
	HiOutlineLink,
	HiArrowTopRightOnSquare,
	HiEnvelope,
	HiCalendarDays,
	HiArrowRight,
	HiOutlineEye,
	HiOutlineEyeSlash,
	HiOutlineDocument,
	HiOutlineGlobeAsiaAustralia,
	HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
	PiHouseDuotone,
	PiUserCircleDuotone,
	PiGridFourDuotone,
	PiBookBookmarkDuotone,
	PiImageDuotone,
} from "react-icons/pi";

import {
	SiNextdotjs,
	SiHtml5,
	SiReact,
	SiDocker,
	SiKubernetes,
	SiCss3,
	SiBootstrap,
	SiNodedotjs,
	SiJquery,
	SiMongodb,
	SiWechat,
	SiUnity,
	SiNginx,
	SiXiaohongshu,
	SiFigma,
	SiSupabase,
	SiFirebase,
	SiVuedotjs,
	SiHtcvive,
	SiAdobelightroom,
} from "react-icons/si";

import {
	FaDiscord,
	FaGithub,
	FaYoutube,
	FaLinkedin,
	FaX,
	FaThreads,
	FaXTwitter,
	FaFacebook,
	FaPinterest,
	FaWhatsapp,
	FaReddit,
	FaTelegram,
	FaNetworkWired,
	FaGitAlt,
	FaFileCode,
	FaLinux,
	FaCameraRetro,
	FaVideo,
} from "react-icons/fa6";

import { DiJavascript } from "react-icons/di";

import {
	TbBrandCSharp,
	TbAugmentedReality,
	TbPlayerPlayFilled,
} from "react-icons/tb";

import { BiLogoPostgresql } from "react-icons/bi";

import { IoLanguage } from "react-icons/io5";

import {
	MdMovieEdit,
	MdMovieCreation,
	MdOutlinePerson,
	MdOutlineNightlight,
	MdOutlineLightMode,
} from "react-icons/md";

export const iconLibrary = {
	arrowUpRight: HiArrowUpRight,
	arrowRight: HiArrowRight,
	email: HiEnvelope,
	globe: HiOutlineGlobeAsiaAustralia,
	person: MdOutlinePerson,
	grid: PiGridFourDuotone,
	book: PiBookBookmarkDuotone,
	openLink: HiOutlineLink,
	calendar: HiCalendarDays,
	home: PiHouseDuotone,
	gallery: PiImageDuotone,
	discord: FaDiscord,
	eye: HiOutlineEye,
	eyeOff: HiOutlineEyeSlash,
	github: FaGithub,
	youtube: FaYoutube,
	xiaohongshu: SiXiaohongshu,
	linkedin: FaLinkedin,
	x: FaX,
	twitter: FaXTwitter,
	threads: FaThreads,
	arrowUpRightFromSquare: HiArrowTopRightOnSquare,
	document: HiOutlineDocument,
	rocket: HiOutlineRocketLaunch,
	javascript: DiJavascript,
	nextjs: SiNextdotjs,
	supabase: SiSupabase,
	figma: SiFigma,
	facebook: FaFacebook,
	pinterest: FaPinterest,
	whatsapp: FaWhatsapp,
	reddit: FaReddit,
	telegram: FaTelegram,
	html: SiHtml5,
	reactjs: SiReact,
	docker: SiDocker,
	k8s: SiKubernetes,
	css: SiCss3,
	bootstrap: SiBootstrap,
	nodejs: SiNodedotjs,
	mongodb: SiMongodb,
	wechat: SiWechat,
	unity: SiUnity,
	jquery: SiJquery,
	nginx: SiNginx,
	firebase: SiFirebase,
	vuejs: SiVuedotjs,
	network: FaNetworkWired,
	git: FaGitAlt,
	csharp: TbBrandCSharp,
	code: FaFileCode,
	vive: SiHtcvive,
	ar: TbAugmentedReality,
	postgresql: BiLogoPostgresql,
	linux: FaLinux,
	camera: FaCameraRetro,
	video: FaVideo,
	medit: MdMovieEdit,
	mcreate: MdMovieCreation,
	lightroom: SiAdobelightroom,
	nightmode: MdOutlineNightlight,
	lightmode: MdOutlineLightMode,
	language: IoLanguage,
	videoPlayer: TbPlayerPlayFilled,
};
